# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multi_lora_decoding.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19multi_lora_decoding.proto"\x15\n\x13ListAdaptersRequest"c\n\x14ListAdaptersResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12#\n\radapter_infos\x18\x03 \x03(\x0b\x32\x0c.AdapterInfo"\x82\x01\n\x0b\x41\x64\x61pterInfo\x12\x12\n\nadapter_id\x18\x01 \x01(\t\x12\x14\n\x0cloading_cost\x18\x02 \x01(\x03\x12\x10\n\x08size_hbm\x18\x03 \x01(\x03\x12\x10\n\x08size_cpu\x18\x04 \x01(\x03\x12\x15\n\rlast_accessed\x18\x05 \x01(\x02\x12\x0e\n\x06status\x18\x06 \x01(\t">\n\x12LoadAdapterRequest\x12\x12\n\nadapter_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x64\x61pter_path\x18\x02 \x01(\t"=\n\x13LoadAdapterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t"*\n\x14UnloadAdapterRequest\x12\x12\n\nadapter_id\x18\x01 \x01(\t"?\n\x15UnloadAdapterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\xc7\x01\n\x02v1\x12\x37\n\x06models\x12\x14.ListAdaptersRequest\x1a\x15.ListAdaptersResponse"\x00\x12@\n\x11load_lora_adapter\x12\x13.LoadAdapterRequest\x1a\x14.LoadAdapterResponse"\x00\x12\x46\n\x13unload_lora_adapter\x12\x15.UnloadAdapterRequest\x1a\x16.UnloadAdapterResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "multi_lora_decoding_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals["_LISTADAPTERSREQUEST"]._serialized_start = 29
  _globals["_LISTADAPTERSREQUEST"]._serialized_end = 50
  _globals["_LISTADAPTERSRESPONSE"]._serialized_start = 52
  _globals["_LISTADAPTERSRESPONSE"]._serialized_end = 151
  _globals["_ADAPTERINFO"]._serialized_start = 154
  _globals["_ADAPTERINFO"]._serialized_end = 284
  _globals["_LOADADAPTERREQUEST"]._serialized_start = 286
  _globals["_LOADADAPTERREQUEST"]._serialized_end = 348
  _globals["_LOADADAPTERRESPONSE"]._serialized_start = 350
  _globals["_LOADADAPTERRESPONSE"]._serialized_end = 411
  _globals["_UNLOADADAPTERREQUEST"]._serialized_start = 413
  _globals["_UNLOADADAPTERREQUEST"]._serialized_end = 455
  _globals["_UNLOADADAPTERRESPONSE"]._serialized_start = 457
  _globals["_UNLOADADAPTERRESPONSE"]._serialized_end = 520
  _globals["_V1"]._serialized_start = 523
  _globals["_V1"]._serialized_end = 722
# @@protoc_insertion_point(module_scope)
