# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from jetstream.core.proto import multi_lora_decoding_pb2 as multi__lora__decoding__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in multi_lora_decoding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class v1Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.completions = channel.unary_stream(
                '/v1/completions',
                request_serializer=multi__lora__decoding__pb2.CompletionRequest.SerializeToString,
                response_deserializer=multi__lora__decoding__pb2.CompletionResponse.FromString,
                _registered_method=True)
        self.models = channel.unary_unary(
                '/v1/models',
                request_serializer=multi__lora__decoding__pb2.ListAdaptersRequest.SerializeToString,
                response_deserializer=multi__lora__decoding__pb2.ListAdaptersResponse.FromString,
                _registered_method=True)
        self.load_lora_adapter = channel.unary_unary(
                '/v1/load_lora_adapter',
                request_serializer=multi__lora__decoding__pb2.LoadAdapterRequest.SerializeToString,
                response_deserializer=multi__lora__decoding__pb2.LoadAdapterResponse.FromString,
                _registered_method=True)
        self.unload_lora_adapter = channel.unary_unary(
                '/v1/unload_lora_adapter',
                request_serializer=multi__lora__decoding__pb2.UnloadAdapterRequest.SerializeToString,
                response_deserializer=multi__lora__decoding__pb2.UnloadAdapterResponse.FromString,
                _registered_method=True)


class v1Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def completions(self, request, context):
        """Generate text based on a prompt. Supports streaming responses.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def models(self, request, context):
        """Lists all the currently loaded LoRA adapters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def load_lora_adapter(self, request, context):
        """Loads a new LoRA adapter.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unload_lora_adapter(self, request, context):
        """Unloads a LoRA adapter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_v1Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'completions': grpc.unary_stream_rpc_method_handler(
                    servicer.completions,
                    request_deserializer=multi__lora__decoding__pb2.CompletionRequest.FromString,
                    response_serializer=multi__lora__decoding__pb2.CompletionResponse.SerializeToString,
            ),
            'models': grpc.unary_unary_rpc_method_handler(
                    servicer.models,
                    request_deserializer=multi__lora__decoding__pb2.ListAdaptersRequest.FromString,
                    response_serializer=multi__lora__decoding__pb2.ListAdaptersResponse.SerializeToString,
            ),
            'load_lora_adapter': grpc.unary_unary_rpc_method_handler(
                    servicer.load_lora_adapter,
                    request_deserializer=multi__lora__decoding__pb2.LoadAdapterRequest.FromString,
                    response_serializer=multi__lora__decoding__pb2.LoadAdapterResponse.SerializeToString,
            ),
            'unload_lora_adapter': grpc.unary_unary_rpc_method_handler(
                    servicer.unload_lora_adapter,
                    request_deserializer=multi__lora__decoding__pb2.UnloadAdapterRequest.FromString,
                    response_serializer=multi__lora__decoding__pb2.UnloadAdapterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('v1', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class v1(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def completions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/v1/completions',
            multi__lora__decoding__pb2.CompletionRequest.SerializeToString,
            multi__lora__decoding__pb2.CompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def models(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1/models',
            multi__lora__decoding__pb2.ListAdaptersRequest.SerializeToString,
            multi__lora__decoding__pb2.ListAdaptersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def load_lora_adapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1/load_lora_adapter',
            multi__lora__decoding__pb2.LoadAdapterRequest.SerializeToString,
            multi__lora__decoding__pb2.LoadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unload_lora_adapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/v1/unload_lora_adapter',
            multi__lora__decoding__pb2.UnloadAdapterRequest.SerializeToString,
            multi__lora__decoding__pb2.UnloadAdapterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
