# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: jetstream/engine/tokenizer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n jetstream/engine/tokenizer.proto\x12\x06\x65ngine"\x96\x01\n\x13TokenizerParameters\x12\x0c\n\x04path\x18\x01 \x01(\t\x12-\n\x0etokenizer_type\x18\x02 \x01(\x0e\x32\x15.engine.TokenizerType\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x19\n\x11use_chat_template\x18\x04 \x01(\x08\x12\x11\n\textra_ids\x18\x05 \x01(\x05*A\n\rTokenizerType\x12\x0c\n\x08tiktoken\x10\x00\x12\x11\n\rsentencepiece\x10\x01\x12\x0f\n\x0bhuggingface\x10\x02\x42\x02P\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "jetstream.engine.tokenizer_pb2", _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals["DESCRIPTOR"]._options = None
  _globals["DESCRIPTOR"]._serialized_options = b"P\001"
  _globals["_TOKENIZERTYPE"]._serialized_start = 197
  _globals["_TOKENIZERTYPE"]._serialized_end = 262
  _globals["_TOKENIZERPARAMETERS"]._serialized_start = 45
  _globals["_TOKENIZERPARAMETERS"]._serialized_end = 195
# @@protoc_insertion_point(module_scope)
