# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tokenizer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftokenizer.proto\x12\x06\x65ngine\"{\n\x13TokenizerParameters\x12\x0c\n\x04path\x18\x01 \x01(\t\x12-\n\x0etokenizer_type\x18\x02 \x01(\x0e\x32\x15.engine.TokenizerType\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x11\n\textra_ids\x18\x04 \x01(\x05*A\n\rTokenizerType\x12\x0c\n\x08tiktoken\x10\x00\x12\x11\n\rsentencepiece\x10\x01\x12\x0f\n\x0bhuggingface\x10\x02\x42\x02P\x01\x62\x06proto3')

_TOKENIZERTYPE = DESCRIPTOR.enum_types_by_name['TokenizerType']
TokenizerType = enum_type_wrapper.EnumTypeWrapper(_TOKENIZERTYPE)
tiktoken = 0
sentencepiece = 1
huggingface = 2


_TOKENIZERPARAMETERS = DESCRIPTOR.message_types_by_name['TokenizerParameters']
TokenizerParameters = _reflection.GeneratedProtocolMessageType('TokenizerParameters', (_message.Message,), {
  'DESCRIPTOR' : _TOKENIZERPARAMETERS,
  '__module__' : 'tokenizer_pb2'
  # @@protoc_insertion_point(class_scope:engine.TokenizerParameters)
  })
_sym_db.RegisterMessage(TokenizerParameters)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001'
  _TOKENIZERTYPE._serialized_start=152
  _TOKENIZERTYPE._serialized_end=217
  _TOKENIZERPARAMETERS._serialized_start=27
  _TOKENIZERPARAMETERS._serialized_end=150
# @@protoc_insertion_point(module_scope)
